name: IZDecode
description: JavaScript Deobfuscator and Unpacker
version: 1.1.0
author: Zzbaivong
author_email: izug.vn@gmail.com
url: https://izugvn.github.io
baseurl: /decodejs
license: MIT

theme: jekyll-theme-cayman
show_downloads: false
google_analytics: UA-106940288-1
sass:
  style: compressed
